name: Mises à jour quotidiennes du README

on:
  schedule:
    - cron: '0 0 * * *'
  
  # Permet de lancer l'action manuellement si besoin
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Modifier le README
        run: |
          NEW_DATE="*Dernière mise à jour le : $(date +'%Y-%m-%d %H:%M:%S') UTC*"
          
          if grep -q "\*Dernière mise à jour le :" README.md; then
            sed -i "s|\*Dernière mise à jour le :.*|$NEW_DATE|" README.md
          else
            echo -e "\n$NEW_DATE" >> README.md
          fi

      - name: Commit et Push des modifications
        run: |
          git config --global user.name "MathysFernandez"
          git config --global user.email "mathys.fernandez5572@gmail.com"
          
          git add README.md
          git commit -m "Mise à jour du README" || echo "modification du README"
          git pull --rebase
          git push