name: Mises à jour du README

on:
  schedule:
    # Se déclenche toutes les 4 heures
    - cron: '12 */4 * * *'
  
  # Permet de lancer l'action manuellement si besoin
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Loterie d'exécution (Décision aléatoire)
        id: random_check
        run: |

          # Génère un nombre aléatoire (0 ou 1)
          # 50% de chances que la variable proceed soit 'true'
          if [ $((RANDOM % 2)) -eq 1 ]; then

            echo "proceed=true" >> "$GITHUB_OUTPUT"
            echo "Loterie gagnée : le README va être mis à jour !"

          else

            echo "proceed=false" >> "$GITHUB_OUTPUT"
            echo "Loterie perdue : pas de mise à jour cette fois-ci."

          fi

      - name: Récupérer le code du dépôt

        # S'exécute SI la loterie est gagnée OU SI le workflow est lancé manuellement
        if: steps.random_check.outputs.proceed == 'true' || github.event_name == 'workflow_dispatch'

        uses: actions/checkout@v4

      - name: Modifier le README
        if: steps.random_check.outputs.proceed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          NEW_DATE="*Last updated: $(date +'%Y-%m-%d %H:%M:%S') UTC*"
          
          if grep -q "\*Last updated:" README.md; then
            sed -i "s|\*Last updated:.*|$NEW_DATE|" README.md
          else
            echo -e "\n$NEW_DATE" >> README.md
          fi

      - name: Commit et Push des modifications
        if: steps.random_check.outputs.proceed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name "MathysFernandez"
          git config --global user.email "mathys.fernandez5572@gmail.com"
          
          git add README.md
          git commit -m "README UPDATE" || echo "README UPDATE"
          git pull --rebase
          git push
